### ISSUE TITLE
confirm_address_payment() doesn't always return a tuple

### ISSUE THREAD

**Issue by trhr** [ydaniels/HD-Merchant-wallet#1]
if I'm reading this error message right, if the wallet's never been used, the function won't return anything.

does that sound about right?

**Comment by ydaniels** [comment]
I am not sure i understand the error you are getting but If no transaction is found on an address its going to return this tuple  (BitcoinBackend.NO_HASH_ADDRESS_BALANCE, None).

**Comment by trhr** [comment]
status, value = class.confirm_address_payment(.... is throwing a NoneType error. i think your if/elses are aligned funny, because I fixed it by adding an else: return (NO_HASH_ADDRESS_BALANCE, None) at the bottom of the function.

**Comment by ydaniels** [comment]
Yea you are right i missed that . Thanks
